---
title: "Analysis PAL: Behavioural Data"
author: "Irene Sophia Plank"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)           # kable
library(tidyverse)       # tibble stuff
library(ggplot2)         # plots
library(ggstatsplot)     # ggplot with stats
library(pastecs)
library(ggrain)
library(cowplot)
library(readr)

dt.path = paste('/home/emba/Documents/EMBA', 'BVET', sep = "/")
knitr::opts_knit$set(root.dir = dt.path)

```

## R Markdown

<style type="text/css">
.main-container {
  max-width: 1100px;
  margin-left: auto;
  margin-right: auto;
}
</style>

# Behavioural data

```{r load_data, warning=F, message=F}
# load the relevant data in long format
df.tsk = list.files(path = dt.path, pattern = "PAL-BV_*", full.names = T) %>%
  map_df(~read_csv(., show_col_types = F, col_types = "ccddddccddcd")) %>% 
  filter(is.na(key)|(key != "tstart" & key != "tend")) %>%
  mutate(
    # sometimes participants used other rows instead of the middle one
    # or moved right with their ring finger to plus instead of 6
    key = case_when(
        key == "+" | key == "9" | key == "3" | key == "6" ~ "right",
        key == "7" | key == "1" | key == "4" ~ "left"
      ),
    key_pos = case_when(
      key_pos == "rught" ~ "right",
      T ~ key_pos
    )
    ) %>%
  select(subID, key_pos, trl, key, rt)

# load the information on the trials from the experiment file and merge with data
df.tsk = merge(df.tsk, 
               read_csv(file.path(dt.path, 'PAL_scheme-pic.csv'), show_col_types = F)) %>%
  mutate_if(is.character, as.factor) %>%
  mutate(
    choice = case_when(
           key == "right" & key_pos == "right" ~ "positive",
           key == "left"  & key_pos == "right" ~ "negative",
           key == "right" & key_pos == "left"  ~ "negative",
           key == "left"  & key_pos == "left"  ~ "positive",
           ),
    acc = case_when(emo == choice ~ T,
                    T ~ F),
    rt.cor = case_when(acc == T ~ rt),
    # change factor levels for phase and difficulty
    phase      = fct_relevel(phase, c("prevolatile", "volatile", "postvolatile")),
    difficulty = fct_relevel(difficulty, c("easy", "medium", "difficult"))
  ) %>%
  filter(substr(subID, 1, 3) != "EMO") %>% 
  group_by(subID) %>%
  mutate(
         # replace very short and very long RTs with NAs
         rt.up = quantile(rt.cor, 0.75, na.rm = T) + 1.5 * IQR(rt.cor, na.rm = T),
         rt.cor   = case_when(rt.cor > 200 & rt.cor < rt.up ~ rt.cor),
         use   = case_when(!is.na(rt.cor) & acc ~ TRUE,
                           TRUE ~ FALSE)
         ) %>%
  select(subID, phase, trl, expected, emo, tone, ut, difficulty, rt, rt.cor, acc, use) 

# does anyone have to be excluded?
exc = df.tsk %>% group_by(subID) %>% summarise(acc = mean(use)) %>% filter(acc < 2/3)
exc = as.character(exc$subID)
print(length(exc)) # print how many have to be excluded

# load pilot participants and add to the list
pilot = read_csv(paste0(dt.path, "/pilot-subIDs.csv"))
exc   = c(exc, pilot$subID)

# exclude these participants
df.tsk = df.tsk %>% filter(!(subID %in% exc)) %>%
  arrange(subID, trl)

# calculate standard deviation of reaction times
df.var = df.tsk %>%
  group_by(subID, phase, difficulty, expected) %>%
  summarise(
    rt.var = sd(rt.cor, na.rm = T),
    rt.se  = sd(rt.cor, na.rm = T)/n()
  )

# save data frames
save(file = "df_PAL.RData", list = c("df.tsk", "df.var"))

# how many are still left
length(unique(df.tsk$subID))

```