function [] = invertModelSim(n, m, i, modSpaceRobMean, sim, saveDir)
% Fit the model i to the data generated by the model m by the simulated
% subject n
% Based on hessetal_spirl_analysis/job_runner_5_sim_data_modinv.m
%
% INPUT
%   n                   integer             simulated subject id
%
%   m                   integer             id of the model used to
%                                           generate data
%
%   i                   integer             id of the model to be fitted
%
%   modSpaceRobMean     struct              updated model space with
%                                           empirical priors
%
%   sim                 struct              simulated data
%  
%   saveDir             char array          base output directory
%-----------------------------------------------------------------------------
%
% Copyright (C) 2024 Anna Yurova, Irene Sophia Plank, LMU University Hospital;
%               based on the hessetal_spirl_analysis toolbox by Alex Hess (2024), TNU, ETHZ
%
%
% This file is part of the EMBA_HGF toolbox, which is released under the terms of the GNU General Public
% Licence (GPL), version 3. For further details, see the file LICENSE or <http://www.gnu.org/licenses/>.
%-----------------------------------------------------------------------------

% Set the random number generator options and the optimization algorithm
% This function is called many times through out the code and resets the
% seed for the random number generator every time
options = setupOpt_and_randSeed();

% set up where to save it
save_path = fullfile(saveDir, 'sim', ['sim_sub', num2str(n)]);
if ~exist(save_path, 'dir')
   mkdir(save_path)
end
filename = [save_path filesep 'sim_mod_', convertStringsToChars(modSpaceRobMean(m).name),...
    '_est_mod_', convertStringsToChars(modSpaceRobMean(i).name) '.mat'];

if ~exist(filename, 'file')
    
    fprintf('------------------- sim %d: data based on %d, fitted with %d -------------------\n', ...
        n, m, i) % number of simulation, number of model for simulating, number of model to be fit


    % check whether tbt
    if contains(modSpaceRobMean(i).prc, "tbt")
        u = sim.sub(n,m).data.u;
    else
        u = sim.sub(n,m).data.u(:,1);
    end
    
    % Invert the model
    est = tapas_fitModel(sim.sub(n,m).data.y,... % responses
        u,... % input sequence
        modSpaceRobMean(i).prc_config,... %Prc fitting model
        modSpaceRobMean(i).obs_config,... %Obs fitting model
        options.opt_config); %opt algo
    
    save(filename, '-struct', 'est');

end

end
